"""empty message

Revision ID: 75602a97a280
Revises: f9ab8358c38c
Create Date: 2021-05-17 13:19:58.297348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75602a97a280'
down_revision = 'f9ab8358c38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'birthday',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_employee_birthday'), 'employee', ['birthday'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_birthday'), table_name='employee')
    op.alter_column('employee', 'birthday',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
