"""empty message

Revision ID: fc32ac47705c
Revises: 75602a97a280
Create Date: 2021-05-20 16:10:54.264729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc32ac47705c'
down_revision = '75602a97a280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employee', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employee', 'salary',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'salary',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('employee', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('department', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
